component: layer
name: slide-screenshot-node-modules

inputs:
  region: ap-beijing
  name: slide-screenshot-node-modules
  src:
    src: ../code/node_modules
    targetDir: /node_modules
  runtimes:
    - Nodejs18.15
  description: slide screenshot function npm dependencies
