component: scf
name: slide-screenshot

inputs:
  name: slide_screenshot_web
  namespace: default
  region: ap-beijing
  type: web
  runtime: CustomRuntime
  memorySize: 2048
  timeout: 60
  image:
    imageType: personal
    imageUrl: ${env:TENCENT_SCF_IMAGE_URL}
    imagePort: 9000
  environment:
    variables:
      COS_SECRET_KEY: ${env:COS_SECRET_KEY}
      COS_SECRET_ID: ${env:COS_SECRET_ID}
      COS_BUCKET: class-slides-res-test-1313601664
      COS_REGION: ap-beijing
      HOST: https://test-class-api-online.saasp.vdyoo.com
      SHOT_URL: https://anna0314zy.github.io/designable-editor/test/slide-shot/index.html
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      XDG_CONFIG_HOME: /var/user
